In [7]:
import numpy as np
import scipy as sp
from scipy import linalg as LA
c = np.mat([[3, 2, 0], [1, 1, 0], [0, 5, 1]])
d = np.matrix([0, -1, 2])
inv = LA.inv(c)
inv


array([[  1.00000000e+00,  -2.00000000e+00,  -1.85037171e-18],
       [ -1.00000000e+00,   3.00000000e+00,   1.85037171e-18],
       [  5.00000000e+00,  -1.50000000e+01,   1.00000000e+00]])

In [8]:
lb=LA.solve(c,d.T)


array([[  2.],
       [ -3.],
       [ 17.]])

In [9]:
circulant = LA.solve_circulant(c,d.T)
circulant

array([[-0.45714286, -1.5       , -0.18253968],
       [-0.02857143,  0.5       ,  0.43650794],
       [ 0.68571429,  1.5       , -0.08730159]])

In [10]:
det = LA.det(c)
det

1.0

In [11]:
pinv = LA.pinv(c)
pinv

array([[  1.00000000e+00,  -2.00000000e+00,   7.24952163e-17],
       [ -1.00000000e+00,   3.00000000e+00,  -3.63617450e-17],
       [  5.00000000e+00,  -1.50000000e+01,   1.00000000e+00]])

In [12]:
pinvh = LA.pinvh(c)
pinvh

array([[ 0.32876712,  0.01369863, -0.06849315],
       [ 0.01369863, -0.04109589,  0.20547945],
       [-0.06849315,  0.20547945, -0.02739726]])

In [13]:
norm = LA.norm(c)
norm

6.4031242374328485

In [14]:
la_norm = LA.norm(c,1)
la_norm

8.0

In [16]:
inf_norm = LA.norm(c,np.inf)
inf_norm

6.0

In [17]:
rank = np.linalg.matrix_rank(c)
rank

3

In [18]:
eigvals = LA.eigvals(c)
eigvals


array([ 1.00000000+0.j,  0.26794919+0.j,  3.73205081+0.j])